version: '3'

services:
  app:
    ports:
      - 5000:5000
    environment:
      - SUBSTITUTES_USERNAME: 
      - SUBSTITUTES_PASSWORD: 
      - SUBSTITUTES_URL:
    image: substitutes/substitutes
    build: .
